language: node_js
node_js:
  - "stable"
before_install:
  - npm install -g yarn --cache-min 999999999
cache:
  directories:
  - node_modules
script:
  - unset CI
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branches:
      only:
      - master