language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - unset CI
  - npm test
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branches:
      only:
      - master