export default {
    live:{
        httpPort:8080,
        wsURL:'ws://api.zemuldo.com',
        httpURL:'https://api.zemuldo.com'
    },
    production:{
        httpPort:8080,
        wsURL:'ws://api.zemuldo.com',
        httpURL:'https://api.zemuldo.com'
    },
    dev:{
        httpPort:8080,
        wsURL:'ws://localhost:8090',
        httpURL:'http://localhost:8090'
    },
    development:{
        httpPort:8080,
        wsURL:'ws://localhost:8090',
        httpURL:'http://localhost:8090'
    }
}